<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-14T18:26:37+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      seo.redirect_to_canonical_url
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Spark JHHS',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1452758528,
        'latest_version' => '5.7.5.6',
        'do_page_reindex_check' => false,
        'favicon_fid' => '20',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'maintenance' => array(
        'version_job_page_num' => '182',
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 0,
    ),
);
